# Generated by Django 2.2 on 2020-03-27 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='work_time',
            field=models.TimeField(null=True),
        ),
    ]
